[phases.setup]
nixpkgs = ['python310', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'python -m gunicorn task_management.wsgi:application --log-file -' 