[phases.setup]
nixpkgs = ['python310', 'postgresql']
cmds = ['ln -sf /nix/store/*-python-3.10*/bin/python3 /usr/local/bin/python']

[phases.install]
cmds = ['/usr/local/bin/python -m pip install --upgrade pip', '/usr/local/bin/python -m pip install -r requirements.txt']

[phases.build]
cmds = ['/usr/local/bin/python manage.py collectstatic --noinput']

[start]
cmd = '/usr/local/bin/python -m gunicorn task_management.wsgi:application --log-file -' 